### ISSUE TITLE
JettyWebSocketServer should not use single servlet name for registering servlets

### ISSUE THREAD

**Issue by clumsy** [OpenHFT/Chronicle-Websocket-Jetty#2]
This has led to a very long debug session for me where an incorrect servlet has been used to process my request.

The problem is JettyWebSocketServer uses single "ws-events" name for all servlets:

    public <T> void addServlet(String path, Function<MarshallableOut, T> outWrapper, BiConsumer<WireIn, T> channel) {
        ServletHolder holderEvents = new ServletHolder("ws-events", new JettyServletFactory(outWrapper, channel));
        this.context.addServlet(holderEvents, path);
    }

    public <S, R> void addService(String path, Class<R> responseClass, Function<R, S> serviceFactory) {
        ServletHolder holderEvents = new ServletHolder("ws-events", new JettyServiceFactory(responseClass, serviceFactory));
        this.context.addServlet(holderEvents, path);
    }

Then org.eclipse.jetty.servlet.ServletHandler uses servlet name to put servlet into PathMap:

    pm.put(pathSpec,_servletNameMap.get(finalMapping.getServletName()));

I believe each of the following approaches will do:
- expose ServletContext to addServlet yourself
- introduce name argument in the corresponding methods
- use path (assuming Jetty invariant is there cannot be multiple servlets under exactly same path spec) as the servlet name

**Comment by clumsy** [comment]
Willing to contribute if you share your vision as to what should be the proper way to fix it (e.g. one othe three I've suggested).

**Comment by peter-lawrey** [comment]
My vision is to do what you feel is the simplest and most natural. Happy to
take a pull request with unit test(s)
ᐧ

**Comment by clumsy** [comment]
PR is done, please check #3.
Let me know if something is missing.
