### ISSUE TITLE
Need to release 1.1.4

### ISSUE THREAD

**Issue by scottkidder** [OpenHFT/Chronicle-Websocket-Jetty#6]
latest chronicle-bom cointains chronicle-websocket-jetty 1.1.4

Can we do a release?

**Comment by hft-team-city** [comment]
Released in [Chronicle-Websocket-Jetty-1.19.30](https://github.com/OpenHFT/Chronicle-Websocket-Jetty/releases/chronicle-websocket-jetty-1.19.30), [BOM-2.19.199](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.199)
