### ISSUE TITLE
Doesn't compile with bom 1.15.253

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Websocket-Jetty#7]
Needs updating to the latest bom,.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Websocket-Jetty-1.19.30](https://github.com/OpenHFT/Chronicle-Websocket-Jetty/releases/chronicle-websocket-jetty-1.19.30), [BOM-2.19.199](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.199)
